server:
  port: 8080 # Port to run the application on
spring:
  application:
    name: web-api # Name of the application
  datasource:
    url: jdbc:mysql://localhost:3306/accounts # URL of the database
    username: root # Username of the database
    password: anmol # Password of the database
    driver-class-name: com.mysql.cj.jdbc.Driver # Driver class name of the databases
  jpa:
    # show-sql: true # Show SQL queries in the console
    hibernate:
      ddl-auto: update # Update the database schema automatically
    #      dialect: org.hibernate.dialect.MySQL8Dialect # Dialect of the database
    database-platform: org.hibernate.dialect.MySQLDialect # Dialect of the database
